project:
  type: website
  output-dir: docs

website:
  title: "Austin D. Allen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/adallen93
      - icon: linkedin
        href: https://linkedin.com/in/austindallen

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



