---
title: "About Austin"
---

Currently finishing my master's program at Duke, I will be graduating May of 2025 with a degree in Biostatisticss. I came to Duke from BYU-Idaho studying statistics and data science. Now that I'm close to the end of my schooling, let me tell you about all that comes next.


I’m passionate about leveraging data and machine learning to solve complex problems, particularly in the biomedical and biotech sectors. My primary focus is on developing and applying predictive models that enhance decision-making and drive innovation in healthcare and life sciences.

---

## Skills and Expertise

- **Programming & Tools**: Python, R, SQL, Linux, Shiny
- **Data Science & Machine Learning**: Machine learning algorithms, neural networks, predictive modeling, statistical analysis
- **Database & Research**: Database management, scientific research, large-scale data analysis

---

## What I'm Looking For

I’m seeking roles that align with my expertise in data science and machine learning, with a focus on impactful, real-world applications. While the specific type of data I'll focus on is still evolving. I enjoy the challenge of working with messy EHR data and am fascinated by large-scale 'omics data and could also see myself exploring data from wearable devices or medical imaging. But regardless of the type of data, you will find me in the futre building models that help investigators tackle complex health-related problems.

---

## Areas of Interest
- Neural networks & deep learning
- Biomedical and biotech applications
- Predictive modeling and diagnostics
- Cutting-edge machine learning applications in healthcare

---

View my [resume](./resume.qmd).